menambahkan kata hai
abdurahmanrizal/belajar-git-fosan pull request #1
Opened 2021-03-05 16:51 UTC by abdurahmanrizal

2021-03-05 16:58 UTC, bhagas requested changes

2021-03-05 16:58 UTC, bhagas commented on hello.txt
> +hai
Tugas kamu sekarang 
pertama coba bikin file baru .txt bebas terus isi aja terserah. 
Kedua aku juga ngrubah file hello.txt kamu seharusnya saat nanti kamu push jd conflict, nah aku pengen tau caramu mengatasi conflict dengan memilih incoming change

2021-03-05 23:29 UTC, abdurahmanrizal commented on hello.txt
> +hai
Baik mas, saya kerjakan

2021-03-06 00:48 UTC, bhagas approved these changes
Okee, sekarang boleh di merge ke branch main / master

2021-03-06 13:05 UTC, merged